export type ServiceId = "websites" | "automation" | "voice";
export type InquiryService = ServiceId | "immersive" | "unsure";
export const SERVICE_OPTIONS = [
  { id: "websites", label: "Website Development" }, { id: "automation", label: "AI Automation" },
  { id: "voice", label: "AI Voice Agents" }, { id: "immersive", label: "Interactive 3D Experiences" },
  { id: "unsure", label: "Help me choose" },
] as const;
export type Service = { id: ServiceId; name: string; promise: string; overview: string; offerings: readonly string[]; benefits: readonly string[]; demonstration: string; action: string };
export const SERVICES: readonly Service[] = [
  { id: "websites", name: "Website Development", promise: "Give your business a clear, memorable home online.", overview: "We design and build websites around your audience, content and next action—from a focused landing page to a custom interactive experience.", offerings: ["Modern business websites", "Custom animated websites", "E-commerce solutions", "Landing pages", "Interactive 3D web experiences"], benefits: ["Explain your offer with clear content and useful navigation.", "Make inquiry and purchase journeys easier to follow.", "Adapt layouts to phones, desktops and keyboard navigation.", "Choose animation that supports the content and loading budget.", "Plan maintainable content and features around your team."], demonstration: "Explore a responsive layout concept, or return to the six-scene prototype to see our local 3D work.", action: "Discuss Your Project" },
  { id: "automation", name: "AI Automation", promise: "Connect the steps your team repeats every day.", overview: "We map the handoffs in your business and design an automation around the tools, review rules and exceptions that matter to you.", offerings: ["Business workflow automation", "Lead processing", "Customer inquiry automation", "CRM integrations", "Custom AI-powered business tools"], benefits: ["Keep incoming requests structured and easier to review.", "Route follow-ups using criteria agreed with your team.", "Make the next owner and next action visible.", "Retain human review for exceptions and sensitive decisions."], demonstration: "Run a sample lead workflow and inspect what each stage would prepare. No systems are connected in this demo.", action: "Request a Demo" },
  { id: "voice", name: "AI Voice Agents", promise: "Give every caller a clear next step.", overview: "We design voice workflows for routine questions and booking requests, with clear limits and a path to a person when the conversation needs one.", offerings: ["AI receptionists", "Customer support calls", "Restaurant reservations", "Appointment booking", "Frequently asked questions", "Staff notifications and escalation"], benefits: ["Collect the details staff need to handle a request.", "Guide callers through common questions and booking options.", "Define handoff rules before connecting a phone system.", "Prepare clear summaries for staff to review."], demonstration: "Try a restaurant receptionist conversation with sample availability and a human handoff. This is a simulation, with no phone connection.", action: "Request a Demo" },
];

export type ProjectCategory = "Luxury immersive 3D website" | "Business website" | "AI automation dashboard" | "AI voice receptionist" | "Interactive web experience";
export type Project = {
  id: string; name: string; category: ProjectCategory; status: "Concept Demo" | "In Development" | "Client Project";
  service: InquiryService; overview: string; challenge: string; approach: readonly string[]; capabilities: readonly string[];
  verifiedTechnologies: readonly string[]; verification?: string;
  preview: "cinematic" | "website" | "automation" | "voice" | "interactive";
  demoUrl?: string; thumbnail?: { src: string; alt: string }; video?: { src: string; poster?: string; captions?: string }; credits?: string;
};
export const PROJECTS: readonly Project[] = [
  { id: "cinematic-studio", name: "Beyond Ordinary", category: "Luxury immersive 3D website", status: "Concept Demo", service: "immersive", overview: "The local VeytronaTech prototype: six connected worlds, woven chrome and a reversible scroll journey.", challenge: "Keep a continuous sculptural story readable and responsive while managing WebGL startup and resource ownership.", approach: ["Procedural chrome ribbons and compatible GPU morph targets.", "One persistent canvas with measured GSAP scroll anchors.", "Deferred geometry preparation, shared resources and bounded quality presets."], capabilities: ["Six connected scene transformations", "Desktop/mobile quality presets", "Reduced-motion and WebGL fallbacks"], verifiedTechnologies: ["Next.js", "TypeScript", "React Three Fiber", "Three.js", "GSAP"], verification: "Verified in this local repository. A concept prototype, not a commissioned client result.", preview: "cinematic" },
  { id: "business-layout", name: "A clearer first impression", category: "Business website", status: "Concept Demo", service: "websites", overview: "A responsive business layout study showing a clear offer, service hierarchy and inquiry path.", challenge: "Help a visitor understand the offer and find the next action across screen sizes.", approach: ["A focused opening statement and useful service grouping.", "Responsive content cards with a clear contact action.", "Plan content requirements before designing production pages."], capabilities: ["Desktop/mobile layout preview", "Content hierarchy", "Inquiry pathway"], verifiedTechnologies: ["React", "TypeScript", "CSS"], verification: "Verified for this local HTML/CSS concept preview only; no external integrations.", preview: "website" },
  { id: "lead-workflow", name: "From inquiry to next action", category: "AI automation dashboard", status: "Concept Demo", service: "automation", overview: "An interactive lead-handling simulation with inspectable stages and different follow-up routes.", challenge: "Explain how a lead could move through qualification, review and staff ownership.", approach: ["Model a lead and its next action without connecting external tools.", "Show each draft output and let visitors inspect the workflow.", "Keep review and exceptions explicit."], capabilities: ["Replayable workflow", "Configurable sample lead", "Step-by-step explanation"], verifiedTechnologies: ["React", "TypeScript"], verification: "Verified for this local reducer-driven simulation; no CRM or external AI connection.", preview: "automation" },
  { id: "restaurant-voice", name: "A helpful first conversation", category: "AI voice receptionist", status: "Concept Demo", service: "voice", overview: "A restaurant receptionist simulation that gathers a table request and demonstrates escalation to a host.", challenge: "Show where a voice agent can assist and where a human should take over.", approach: ["Use a scripted conversation with visible sample availability.", "Keep reservation requests in draft status.", "Preview a staff summary and human handoff."], capabilities: ["Configurable party size and time", "Audible receptionist and transcript", "Voice and speed controls", "Staff and handoff previews"], verifiedTechnologies: ["React", "TypeScript", "Web Speech API"], verification: "Local scripted demo with browser SpeechSynthesis. No live conversational AI or phone integration.", preview: "voice" },
  { id: "spatial-interface", name: "Shape the atmosphere", category: "Interactive web experience", status: "Concept Demo", service: "immersive", overview: "A lightweight spatial interface study with selectable geometry and lighting treatments.", challenge: "Let visitors explore a visual direction without loading another 3D engine or canvas.", approach: ["Build an HTML/CSS study with explicit user controls.", "Offer shape and palette choices with a static reduced-motion state.", "Use the study as a starting point for discussing a production experience."], capabilities: ["Interactive shape controls", "Palette exploration", "Lightweight responsive preview"], verifiedTechnologies: ["React", "CSS"], verification: "Verified for the code-native shape and palette study. It does not create a second WebGL canvas.", preview: "interactive" },
];
// Reject executable/unconfigured destinations when real project data is added.
export function safeDemoUrl(value?: string) {
  if (!value) return undefined;
  if (/^\/(?!\/)[^\\\s]*$/.test(value)) return value;
  try { const url = new URL(value); return url.protocol === "https:" && !url.username && !url.password ? url.href : undefined; } catch { return undefined; }
}
