import type { Metadata } from "next";
import { SERVICES } from "@/lib/business-data";
import { CONTACT_EMAIL } from "@/lib/inquiry";
import { siteOrigin } from "@/lib/site-config";
const origin = siteOrigin();
export const metadata: Metadata = { title:"Websites, AI Automation & Voice Workflows — VeytronaTech",description:"Explore VeytronaTech website development, AI automation, voice agent design and immersive 3D services. Discuss scope, systems and human review before building.",...(origin ? {alternates:{canonical:"/services"},openGraph:{url:`${origin}/services`,title:"VeytronaTech Services"}} : {}) };
export default function ServicesPage() {
  const structured = {"@context":"https://schema.org","@type":"Organization",name:"VeytronaTech",email:CONTACT_EMAIL,...(origin ? {url:origin} : {}),description:"Website development, interactive 3D experiences, AI automation and voice workflow design."};
  return <div className="service-page"><a className="skip-link" href="#service-content">Skip to services</a><header className="service-page-nav"><a className="studio-wordmark" href="/">VEYTRONA<span>TECH</span></a><a className="studio-button secondary" href="/#contact">Discuss your project ↗</a></header><main id="service-content" tabIndex={-1}><p className="panel-kicker">VEYTRONATECH / OUR SERVICES</p><h1>Digital experiences with a clear purpose.</h1><p className="panel-intro">We build around your audience, the tools you use and the next action you want to make easier. Explore the possibilities, then discuss the scope with us.</p><div className="service-page-grid">{SERVICES.map(service => <article key={service.id} id={service.id}><p className="panel-kicker">{service.name}</p><h2>{service.promise}</h2><p>{service.overview}</p><h3>What we can build</h3><ul className="benefit-list">{service.offerings.map(item => <li key={item}>{item}</li>)}</ul><h3>Designed to help you</h3><ul className="benefit-list">{service.benefits.map(item => <li key={item}>{item}</li>)}</ul><a className="text-button" href={`mailto:${CONTACT_EMAIL}?subject=${encodeURIComponent(`${service.name} inquiry — VeytronaTech`)}`}>{service.action} ↗</a></article>)}</div><section className="service-page-ending"><h2>Explore before you commit.</h2><p>Our cinematic website and interactive studio show concept work and simulated workflows. No client results, live phone connections or completed third-party integrations are claimed by these demos.</p><div className="panel-actions"><a className="studio-button" href="/">Explore the cinematic studio ↗</a><a className="text-button email-address" href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL} ↗</a></div></section></main><footer>VEYTRONATECH · BEYOND ORDINARY</footer><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structured).replace(/</g,"\\u003c")}} /></div>;
}
